name: CI2

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  # https://docs.docker.com/build/ci/github-actions/reproducible-builds/
  SOURCE_DATE_EPOCH: 0
  # https://docs.docker.com/build/ci/github-actions/build-summary/#disable-job-summary
  DOCKER_BUILD_SUMMARY: false

jobs:
  build_images:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read
      id-token: write

    steps:
      -
        name: Checkout
        uses: actions/checkout@v5
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Log in to container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io/${{ github.repository_owner }}/hello2
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          outputs: "type=image,name=ghcr.io/${{ github.repository_owner }}/hello2,annotation-index.org.opencontainers.image.description=My multi-arch image"
